### ISSUE TITLE
Create django project

### ISSUE THREAD

**Issue by ghost** [khukie-air/KHUKIE-Air#1]
We need to create a django project named KHUKIE-Air.

I think that it has two applications.
First app has to provide APIs that connect AWS S3 with users.
Second app has to provide APIs that provide service accesssibility and convenience to users.

Should we create?

**Comment by freckie** [comment]
쟝고 프로젝트를 생성할 때 대시(-)가 들어갈 수 없어서 khukieAir 로 생성했습니다.
하위 App으로 UserApp, S3App 생성했습니다.
